// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDw-9ft-jDQOGddsEJWFm7SHkxAT8F8Io',
    appId: '1:87868641539:web:35fc12d995e5803d0d1936',
    messagingSenderId: '87868641539',
    projectId: 'fir-flutter-codelab-50a8a',
    authDomain: 'fir-flutter-codelab-50a8a.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-50a8a.appspot.com',
    measurementId: 'G-7V4RQ2Z9YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9Ik7zFcsByA3iiE7iPylbJn4Ppw5weM',
    appId: '1:87868641539:android:984fc54fdf63d0120d1936',
    messagingSenderId: '87868641539',
    projectId: 'fir-flutter-codelab-50a8a',
    storageBucket: 'fir-flutter-codelab-50a8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIie91sZxrZ1VWVl9SUyNL06zBBzl3ZLY',
    appId: '1:87868641539:ios:70976b2a1a02d2910d1936',
    messagingSenderId: '87868641539',
    projectId: 'fir-flutter-codelab-50a8a',
    storageBucket: 'fir-flutter-codelab-50a8a.appspot.com',
    iosClientId: '87868641539-2qlsbuoj9srvlk319j29gomc6rqa573p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIie91sZxrZ1VWVl9SUyNL06zBBzl3ZLY',
    appId: '1:87868641539:ios:70976b2a1a02d2910d1936',
    messagingSenderId: '87868641539',
    projectId: 'fir-flutter-codelab-50a8a',
    storageBucket: 'fir-flutter-codelab-50a8a.appspot.com',
    iosClientId: '87868641539-2qlsbuoj9srvlk319j29gomc6rqa573p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
